### PR TITLE
ability to display tableName in Excel files.

### PR DESCRIPTION
**Pull request by simogeo**
- Adding ability to display tableName in Excel files.
- `th` and `td` matches in thead loop

### CODE REVIEW

**Comment by simogeo** [comment]
@hhurz : I'm happy to see that someone is maintaining this project. Just discover the fork right now. Thanks for the great work.

No way to report issue on your fork, is that intentional ?

I have the impression that this [jquery.base64.js](https://raw.githubusercontent.com/kayalshri/tableExport.jquery.plugin/master/jquery.base64.js) file is more UTF-8 compatible than yours ? Is that possible? Tested with libreOffice only.

**Comment by simogeo** [comment]
@adks3489 : please read my last comment since you pulled the last  jquery.base64.js file

**Comment by simogeo** [comment]
@adks3489, @hhurz : 
Regarding UTF-8 and  jquery.base64.js, I've seen in the code (around L358) : 

> downloadFile(defaults.fileName+'.'+extension, 'data:application/vnd.ms-'+defaults.type+';base64,' + base64data);

and tried : 

downloadFile(defaults.fileName+'.'+extension, 'data:application/vnd.ms-'+defaults.type+';charset=utf-8;base64,' + base64data);

But I get the same encoding accent problem

**Comment by hhurz** [comment]
@simogeo: ty for your contribution. Regarding issue reporting: im trying to figure out why thats not possible.

**Comment by simogeo** [comment]
@hhurz : you can set it up into https://github.com/hhurz/tableExport.jquery.plugin/settings under the  `Features` tab

**Pull request merged**
