### PR TITLE
Update jspdf.min.js

### PR DESCRIPTION
**Pull request by reubenbrown**

### CODE REVIEW

**Comment by hhurz** [comment]
There is a known bug in jsPDF 1.1.135 which prevents me to update jspdf.min.js. See https://github.com/MrRio/jsPDF/issues/519 and https://github.com/MrRio/jsPDF/issues/525 for further information. Also exists a pull request https://github.com/MrRio/jsPDF/pull/517 there, which has not been merged until know.

**Comment by reubenbrown** [comment]
Yes I ran into the bug as well after upgrading my local version of jsPDF and making this pull request noticing all my tests were failing. 

I'm testing [MrRio/jsPDF#517](https://github.com/MrRio/jsPDF/pull/517) locally as a quick fix hopefully they'll merge it in soon

**Comment by reubenbrown** [comment]
@hhurz Updated `jspdf.min.js` to version 1.1.239 which should resolve the previously noted bugs

**Comment by hhurz** [comment]
@reubenbrown Thanks for testing!

**Pull request merged**
